### ISSUE TITLE
Fireballs persist through floor resets

### ISSUE THREAD

**Issue by PartiallyTyped** [Unity-Technologies/obstacle-tower-source#14]
Going to a high level floor and losing or going up/down a level doesn't 'destroy' the fireball objects.

Steps to reproduce:

1. Start the environment. 
2. Go to high level eg. 99. 
3. Lose/reset the game. 

On the left, the fireball objects persist through floors.

**Comment by awjuliani** [comment]
Hi @Solliet 

This is actually by-design. The persistence of the fireballs corresponds to a cache of gameobjects which are kept and selectively turned on and off.

**Comment by Solliet** [comment]
Hi @awjuliani 

Thanks for the clarification. Wouldn't this cause performance degradation if they stack up?

**Comment by awjuliani** [comment]
As long as the game objects are disabled, there should be minimal performance impact.
