### ISSUE TITLE
[issue] No protocol specified

### ISSUE THREAD

**Issue by PartiallyTyped** [Unity-Technologies/obstacle-tower-source#18]
Hi @awjuliani ,
I am trying to run the obstacle tower on a remote machine without root credentials. Running it through `ssh` I get the following:
```
~/.obstacle/obstacletower.x86_64 
No protocol specified
Found path: /home/stelios/.obstacle/obstacletower.x86_64
No protocol specified
```

**Comment by awjuliani** [comment]
Hi @Solliet 

It seems that this error is not specific to Obstacle Tower, but instead related to the graphics set-up of your remote machine. Can you tell me a little more about what you have running on the machine?

**Comment by Solliet** [comment]
The machine is running `ubuntu 18.04` on an i7 8700k, nvidia 2080ti. 

Simply executing `~/.obstacle/obstacletower.x86_64 ` causes the terminal to hangup. Running ` xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' ~/.obstacle/obstacletower.x86_64 --nographics` results in: `Found path: /home/stelios/.obstacle/obstacletower.x86_64` and then the terminal exits.

**Comment by awjuliani** [comment]
Hi @Solliet 

Are you able to run any other Unity/ML-Agents binaries by chance? If not, then the issue might be best asked on the ML-Agents forums, or github page. Unfortunately I am not familiar with this issue myself.
