### ISSUE TITLE
Door does not render properly in Future Theme

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/obstacle-tower-source#24]
![door_future_bug](https://user-images.githubusercontent.com/6996955/86328989-d9bc8f00-bc45-11ea-83d1-965aafdcc956.png)

Windows 10, Unity v2019.4.1f1

Shader: FT_GL_ForceField
Material: FT_ME_DoorRegular

**Comment by MarcoMeter** [comment]
Same issue on the build from the registry
![door_future_bug](https://user-images.githubusercontent.com/6996955/86336302-fc53a580-bc4f-11ea-84f3-5e9ecf9ca83d.png)

**Comment by MarcoMeter** [comment]
@awjuliani 
This bug is caused by updating Unity  to >2019.3.

I narrowed down the problem to the FT_GL_ForceField shader. The property AlphaBlockAmount misbehaves now.
It has to be set to 0 if something should be visible.

Further, I noted that the animations of these doors do not work properly as well. Instead of moving up, they instantly vanish.

**Comment by MarcoMeter** [comment]
Before

![shadergraph](https://user-images.githubusercontent.com/6996955/86448727-756a0000-bd17-11ea-87ee-bef6cbffbb7b.png)

After

![mat2](https://user-images.githubusercontent.com/6996955/86448741-7a2eb400-bd17-11ea-8dbf-a02fee41455f.png)

**Comment by MarcoMeter** [comment]
The door animation bug is caused by this shader issue as well, because the animation affects the AlphaBlockAmount value.

**Comment by awjuliani** [comment]
Thanks for pointing this out Marco, we are taking a look internally, and will hopefully have a fix soon.

**Comment by MarcoMeter** [comment]
If that particular bug requires more afford, I'd suggest to downgrade to Unity v2019.2.21f.

**Comment by awjuliani** [comment]
We should be able to address it without the need for a downgrade. I have reached out to the person who originally created the shader/material, and he is taking a look at it this week.

**Comment by MarcoMeter** [comment]
Bug looks fixed to me
